version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 10
    versioning-strategy: "auto"
    ignore:
      # Ignore gh-pages updates until we can update angular-cli-ghpages
      - dependency-name: "gh-pages"
